object frmResults: TfrmResults
  Left = 179
  Top = 220
  BorderIcons = [biSystemMenu]
  BorderStyle = bsSingle
  Caption = 'Results'
  ClientHeight = 465
  ClientWidth = 802
  Color = clGradientActiveCaption
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
  object sgResults: TStringGrid
    Left = 16
    Top = 56
    Width = 769
    Height = 393
    ColCount = 2
    DefaultColWidth = 382
    FixedCols = 0
    RowCount = 2
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Montserrat'
    Font.Style = []
    ParentFont = False
    ScrollBars = ssVertical
    TabOrder = 0
  end
  object btnPrint: TButton
    Left = 16
    Top = 16
    Width = 513
    Height = 33
    Caption = 'Print'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Montserrat'
    Font.Style = []
    ParentFont = False
    TabOrder = 1
    OnClick = btnPrintClick
  end
  object cbPrinters: TComboBox
    Left = 536
    Top = 16
    Width = 249
    Height = 31
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -20
    Font.Name = 'Montserrat'
    Font.Style = []
    ItemHeight = 23
    ParentFont = False
    TabOrder = 2
    Text = 'cbPrinters'
    OnDropDown = cbPrintersDropDown
  end
end
